---
- hosts: all
  become: true

  roles:
    - setup
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.pip
    - geerlingguy.docker
    - unbound
    - pihole
    #- role: unifi
