---
- hosts: all
  gather_facts: false
  become: false

  pre_tasks:
    - name: Set custom ssh port.
      import_tasks: tasks/ssh_juggle_port.yml

- hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - setup
    - geerlingguy.pip
    - geerlingguy.docker
    #- role: pihole
    #- role: unifi
