---
- hosts: all
  become: true
  gather_facts: false

  pre_tasks:
  - name: Port juggle
    import_tasks: tasks/port_juggle.yml
  
  - name: Gather facts
    setup:
    tags: setup

  - name: System setup
    import_tasks: tasks/system.yml
    tags: system

  roles:
    - role: geerlingguy.security
    - role: geerlingguy.firewall
    - role: geerlingguy.pip
    - role: geerlingguy.docker_arm

  tasks:
    - import_tasks: tasks/user.yml
      tags: setup