---
- name: "Add user to the docker group"
  user:
    name: "{{ username }}"
    groups:
      - docker
    append: true
  
- name: Set message of the day.
  copy:
    src: motd
    dest: "/etc"
    mode: 0644
