---
- name: "Create user."
  user:
    name: "{{ username }}"
    shell: /bin/bash
    groups:
      - sudo
      - users
    state: present
    append: true
    createhome: true

- name: "Add public key to authorized_keys."
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ ssh_public_key }}"
  with_items:
    - "{{ username }}"
    - "{{ ansible_user }}"

