---
- name: "Create groups"
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - admins
    - docker

- name: "Add user to the admin group."
  user:
    name: "{{ username }}"
    groups:
      - sudo
      - admins
      - docker
    append: true

- name: "Add public key to authorized_keys."
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key }}"