---
- name: "Add user to the docker group"
  user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: true
  
- name: Set message of the day.
  copy:
    src: motd
    dest: "/etc"
    mode: 0644

- name: "Add public key to authorized_keys."
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ ssh_public_key }}"
