---
- name: "Create pihole directory."
  file:
    path: "{{ pihole_dir }}"
    state: directory

- name: "Copy pihole docker-compose file to server."
  copy:
    src: docker-compose.yml
    dest: "{{ pihole_dir }}"

- name: "Start pihole"
  community.docker.docker_compose:
    project_src: "{{ pihole_dir }}"
