---
- name: "Create pihole directory."
  file:
    path: "{{ pihole_dir }}"
    state: directory

- name: "Copy pihole docker-compose file to server."
  template:
    src: docker-compose.yml.j2
    dest: "{{ pihole_dir }}/docker-compose.yml"

- name: "Start pihole"
  community.docker.docker_compose:
    project_src: "{{ pihole_dir }}"
    pull: true
